#
# Automatically downloaded from https://raw.githubusercontent.com/raywenderlich/swift-style-guide/master/com.raywenderlich.swiftlint.yml by SwiftLint on 22/08/2022 at 4:40:02 pm.
#

included: # paths to include during linting. `--path` is ignored if present.
  - Source
  - iOS Example Frame
  - iOS Example Frame Carthage
  - iOS Example Frame SPM
  - Tests
  - scripts
  - Documentation

excluded:
  - ${PWD}/Carthage
  - ${PWD}/Pods
  - ${PWD}/DerivedData
  - iOS Example Frame/Pods
  - Carthage
  - Checkout
  - iOS Example Apple Pay
  - iOS Example

disabled_rules:
  - discarded_notification_center_observer
  - notification_center_detachment
  - orphaned_doc_comment
  - todo
  - unused_capture_list
  - switch_case_alignment
  - multiline_arguments
  - multiline_parameters_brackets
  - multiline_literal_brackets
  - class_delegate_protocol

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - colon # promote to error
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - indentation_width
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition


custom_rules:
  array_constructor:
    name: "Array/Dictionary initializer"
    regex: '[let,var] .+ = (\[.+\]\(\))'
    capture_group: 1
    message: "Use explicit type annotation when initializing empty arrays and dictionaries"
    severity: warning

attributes:
  always_on_same_line:
    - "@IBSegueAction"
    - "@IBAction"
    - "@NSManaged"
    - "@objc"
    - "@frozen"

force_cast: warning
force_try: warning
function_body_length:
    warning: 60

legacy_hashing: error

indentation_width:
  indentation_width: 4
  ignores_function_declarations: true
  ignores_comments: true

line_length:
  warning: 140
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

private_over_fileprivate:
  validate_extensions: true

trailing_whitespace:
  ignores_empty_lines: false
  ignores_comments: true
  max_empty_lines: 2

vertical_whitespace:
  max_empty_lines: 2

vertical_whitespace_opening_braces:
  max_empty_lines: 1

cyclomatic_complexity:
    warning: 15

function_parameter_count:
    warning: 10

nesting:

  type_level:
    warning: 3

  function_level:
    warning: 3
