#
# Automatically downloaded from https://raw.githubusercontent.com/raywenderlich/swift-style-guide/master/com.raywenderlich.swiftlint.yml by SwiftLint on 22/08/2022 at 4:40:02 pm.
#

parent_config: https://raw.githubusercontent.com/raywenderlich/swift-style-guide/master/com.raywenderlich.swiftlint.yml

included: # paths to include during linting. `--path` is ignored if present.
  - Source
  - iOS Example Frame
  - iOS Example Frame Carthage
  - iOS Example Frame SPM
  - Tests
  - scripts
  - Documentation

excluded:
  - ${PWD}/Carthage
  - ${PWD}/Pods
  - ${PWD}/DerivedData
  - iOS Example Frame/Pods
  - Carthage
  - Checkout
  - iOS Example Apple Pay
  - iOS Example

disabled_rules:
  - discarded_notification_center_observer
  - notification_center_detachment
  - orphaned_doc_comment
  - todo
  - unused_capture_list
  - switch_case_alignment
  - multiline_arguments
  - multiline_parameters_brackets
  - multiline_literal_brackets
  - class_delegate_protocol

attributes:
  always_on_same_line:
    - "@IBSegueAction"
    - "@IBAction"
    - "@NSManaged"
    - "@objc"
    - "@frozen"

indentation_width:
  indentation_width: 4
  ignores_function_declarations: true
  ignores_comments: true

line_length:
  warning: 140
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

trailing_whitespace:
  ignores_empty_lines: false
  ignores_comments: true
  max_empty_lines: 2

vertical_whitespace:
  max_empty_lines: 2

cyclomatic_complexity:
    warning: 12
    error: 15

nesting:
  type_level:
    warning: 3

  function_level:
    warning: 3

force_unwrapping: warning
