module: Checkout
author: Checkout.com
author_url: https://www.checkout.com/
source_host: github
source_host_url: https://github.com/checkout/frames-ios
source_host_files_url: https://github.com/checkout/frames-ios/tree/master
output: docs
theme: ../.jazzy/.themes/checkout.com
clean: true
documentation: Documentation/**/*.md
min_acl: public
xcodebuild_arguments:
  - -workspace
  - CocoapodsSample/CheckoutCocoapodsSample.xcworkspace
  - -scheme
  - Checkout
  - -destination
  - generic/platform=iOS
